language: generic
sudo: required
services:
  -docker
before_install:
  - docker build -t gweinhei/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gweinhei/docker-react npm run test

deploy:
  provider: elastickbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-783616990833"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
