sudo: required
language: generic
services:
  -docker
before_install:
  - docker build -t gweinhei/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gweinhei/docker-react -- --coverage  